### ISSUE TITLE
PSD1 is missing ProjectURI

### ISSUE THREAD

**Issue by kilasuit** [johnmccrae/New-MyPSModule#1]
**Describe the bug**
ProjectURI in the PSD1 allows users downloading your module to know where to look to raise issues and in the current version pushed to the gallery it is not populated 

**Expected behavior**
PSD1 is properly populated

**Comment by johnmccrae** [comment]
Thanks for the feedback. Will fix that asap

**Comment by johnmccrae** [comment]
Solved. Updated the PSD1 some time ago, and forgot to close this.
